cluster-api-operator:
  core:
    cluster-api:
      version: v1.9.3
      createNamespace: false
  bootstrap:
    kubeadm:
      version: v1.9.3
      createNamespace: false
  controlPlane:
    kubeadm:
      version: v1.9.3
      createNamespace: false
